name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8.1.1
          run_install: |
            - args: [--frozen-lockfile]

      - name: Create Release Pull Request or Publish to github registry
        id: changesets
        uses: changesets/action@v1
        with:
          title: "chore(release): release react-ui"
          commit: "chore(release): release react-ui"
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
          NPM_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
